/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema4_czakozoltan_grupa30225;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zoli
 */
public class BankControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form BankControlPanel
     */
    
    private BussinesLogic logic = new BussinesLogic();
    
    public BankControlPanel() {
        this.logic.getBank().bankInitializer("Accounts.txt",0);
        this.logic.getBank().bankInitializer("SavingAccounts.txt",2);
        this.logic.getBank().bankInitializer("SpendingAccounts.txt",1);
        initComponents();
        this.setLocationRelativeTo(null);
        showAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AccountList = new javax.swing.JList();
        RemoveButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ReportButton = new javax.swing.JButton();
        IBANText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BalanceText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PINText = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        IsWellFormedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Account Control Panel");

        jScrollPane1.setViewportView(AccountList);

        RemoveButton.setText("Remove");
        RemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveButtonMouseClicked(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        ReportButton.setText("Report");
        ReportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("IBAN:");

        jLabel2.setText("Balance:");

        jLabel3.setText("PIN:");

        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal Account", "Spending Account", "Saving Account" }));

        jLabel4.setText("Type:");

        IsWellFormedButton.setText("IsWellFormed");
        IsWellFormedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IsWellFormedButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IsWellFormedButton)
                .addGap(116, 116, 116)
                .addComponent(RemoveButton)
                .addGap(58, 58, 58)
                .addComponent(ReportButton)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AddButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IBANText)
                            .addComponent(BalanceText)
                            .addComponent(PINText)
                            .addComponent(TypeCombo, 0, 207, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IBANText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PINText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(AddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RemoveButton)
                        .addComponent(IsWellFormedButton))
                    .addComponent(ReportButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        
        try {
            this.logic.addNewAccount(this.IBANText.getText(), this.PINText.getText(), this.BalanceText.getText(), this.TypeCombo.getSelectedIndex());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
					  "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ExistingAccountException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
					  "Error", JOptionPane.ERROR_MESSAGE);
        } catch (EmptyFieldException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
					  "Error", JOptionPane.ERROR_MESSAGE);
        }
        showAccounts();
    }//GEN-LAST:event_AddButtonMouseClicked

    private void RemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveButtonMouseClicked
        String IBAN = (String)this.AccountList.getSelectedValue();
        this.logic.removeSelectedAccount(IBAN,this.AccountList.getSelectedIndex());
        showAccounts();
    }//GEN-LAST:event_RemoveButtonMouseClicked

    private void ReportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportButtonMouseClicked
        int success = this.logic.getBank().generateReport();
        
        if(success==0)
        {
            JOptionPane.showMessageDialog(null, "A report has been created  successfully!",
					  "Success", JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error creating report!",
					  "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ReportButtonMouseClicked

    private void IsWellFormedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IsWellFormedButtonMouseClicked
        boolean isWell;
        try
        {
            isWell = this.logic.wellFormed();
            if(isWell)
            {
                JOptionPane.showMessageDialog(null, "This Bank is well formed!",
					  "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "This Bank is not well form! Check your database!",
					  "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(DuplicatedAccountException ex)
        {
            JOptionPane.showMessageDialog(null, "This Bank is not well form! " + ex.getMessage(),
					  "Error", JOptionPane.ERROR_MESSAGE);
        } catch (WrongAccountTypeException ex) {
            JOptionPane.showMessageDialog(null, "This Bank is not well form! " + ex.getMessage(),
					  "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_IsWellFormedButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankControlPanel().setVisible(true);
            }
        });
    }
    
    public void showAccounts()
    {
        this.AccountList.setModel(this.logic.getBank().getAccountList());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AccountList;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField BalanceText;
    private javax.swing.JTextField IBANText;
    private javax.swing.JButton IsWellFormedButton;
    private javax.swing.JTextField PINText;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton ReportButton;
    private javax.swing.JComboBox TypeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
